import type { DesignerTemplate } from '../types/designer';

export const DESIGNER_TEMPLATES: DesignerTemplate[] = [
  // 1. High Availability
  {
    id: 'high-availability',
    name: 'High Availability',
    description: 'AT&T Core (IPE) with dual Hubs and AWS destination. Triangle topology with MPLS uplinks and AWS Interconnect – last mile to cloud.',
    tier: 'maximum',
    nodeCount: 4,
    edgeCount: 4,
    nodes: [
      {
        id: 'ha-ipe-1',
        type: 'network',
        functionType: 'ipe',
        x: 280,
        y: 80,
        name: 'AT&T Core (IPE)',
        icon: 'Network',
        status: 'active',
        config: {},
      },
      {
        id: 'ha-cr-1',
        type: 'function',
        functionType: 'router',
        subType: 'cloud',
        x: 120,
        y: 280,
        name: 'Hub A',
        icon: 'hub',
        status: 'active',
        config: {},
      },
      {
        id: 'ha-cr-2',
        type: 'function',
        functionType: 'router',
        subType: 'cloud',
        x: 440,
        y: 280,
        name: 'Hub B',
        icon: 'hub',
        status: 'active',
        config: {},
      },
      {
        id: 'ha-aws-1',
        type: 'destination',
        functionType: 'destination',
        cloudProvider: 'AWS',
        x: 280,
        y: 380,
        name: 'AWS',
        icon: 'Cloud',
        status: 'active',
        config: { provider: 'AWS', region: 'US East' },
      },
    ],
    edges: [
      {
        id: 'ha-edge-1',
        source: 'ha-ipe-1',
        target: 'ha-cr-1',
        type: 'MPLS',
        bandwidth: '10 Gbps',
        status: 'active',
        config: { resilience: 'ha' },
      },
      {
        id: 'ha-edge-2',
        source: 'ha-ipe-1',
        target: 'ha-cr-2',
        type: 'MPLS',
        bandwidth: '10 Gbps',
        status: 'active',
        config: { resilience: 'ha' },
      },
      {
        id: 'ha-edge-3',
        source: 'ha-cr-1',
        target: 'ha-aws-1',
        type: 'Direct Connect',
        bandwidth: '1 Gbps',
        status: 'active',
      },
      {
        id: 'ha-edge-4',
        source: 'ha-cr-2',
        target: 'ha-aws-1',
        type: 'Direct Connect',
        bandwidth: '1 Gbps',
        status: 'active',
      },
    ],
  },

  // 2. Cloud-to-Cloud Local
  {
    id: 'cloud-to-cloud-local',
    tier: 'standard',
    name: 'Cloud-to-Cloud Local',
    description: 'Hub bridging AWS and Azure in the same region. AWS Interconnect – last mile to AWS, ExpressRoute to Azure.',
    nodeCount: 3,
    edgeCount: 2,
    nodes: [
      {
        id: 'c2c-aws-1',
        type: 'destination',
        functionType: 'destination',
        cloudProvider: 'AWS',
        x: 80,
        y: 200,
        name: 'AWS',
        icon: 'Cloud',
        status: 'active',
        config: { provider: 'AWS', region: 'US East' },
      },
      {
        id: 'c2c-cr-1',
        type: 'function',
        functionType: 'router',
        subType: 'cloud',
        x: 280,
        y: 200,
        name: 'Hub',
        icon: 'hub',
        status: 'active',
        config: {},
      },
      {
        id: 'c2c-azure-1',
        type: 'destination',
        functionType: 'destination',
        cloudProvider: 'Azure',
        x: 480,
        y: 200,
        name: 'Azure',
        icon: 'Cloud',
        status: 'active',
        config: { provider: 'Azure', region: 'US East' },
      },
    ],
    edges: [
      {
        id: 'c2c-edge-1',
        source: 'c2c-cr-1',
        target: 'c2c-aws-1',
        type: 'Direct Connect',
        bandwidth: '1 Gbps',
        status: 'active',
      },
      {
        id: 'c2c-edge-2',
        source: 'c2c-cr-1',
        target: 'c2c-azure-1',
        type: 'ExpressRoute',
        bandwidth: '1 Gbps',
        status: 'active',
      },
    ],
  },

  // 3. Internet-to-Cloud
  {
    id: 'internet-to-cloud',
    tier: 'standard',
    name: 'Internet-to-Cloud',
    description: 'Internet access through a firewall and Hub to AWS. Left-to-right linear chain.',
    nodeCount: 4,
    edgeCount: 3,
    nodes: [
      {
        id: 'i2c-inet-1',
        type: 'network',
        functionType: 'internet',
        x: 60,
        y: 200,
        name: 'Internet',
        icon: 'Globe',
        status: 'active',
        config: {},
      },
      {
        id: 'i2c-fw-1',
        type: 'function',
        functionType: 'firewall',
        x: 200,
        y: 200,
        name: 'Firewall',
        icon: 'Shield',
        status: 'active',
        config: {},
      },
      {
        id: 'i2c-cr-1',
        type: 'function',
        functionType: 'router',
        subType: 'cloud',
        x: 360,
        y: 200,
        name: 'Hub',
        icon: 'hub',
        status: 'active',
        config: {},
      },
      {
        id: 'i2c-aws-1',
        type: 'destination',
        functionType: 'destination',
        cloudProvider: 'AWS',
        x: 520,
        y: 200,
        name: 'AWS',
        icon: 'Cloud',
        status: 'active',
        config: { provider: 'AWS', region: 'US East' },
      },
    ],
    edges: [
      {
        id: 'i2c-edge-1',
        source: 'i2c-inet-1',
        target: 'i2c-fw-1',
        type: 'Internet',
        bandwidth: '1 Gbps',
        status: 'active',
      },
      {
        id: 'i2c-edge-2',
        source: 'i2c-fw-1',
        target: 'i2c-cr-1',
        type: 'Ethernet',
        bandwidth: '1 Gbps',
        status: 'active',
      },
      {
        id: 'i2c-edge-3',
        source: 'i2c-cr-1',
        target: 'i2c-aws-1',
        type: 'Direct Connect',
        bandwidth: '1 Gbps',
        status: 'active',
      },
    ],
  },

  // 4. SD-WAN Hybrid
  {
    id: 'sdwan-hybrid',
    tier: 'standard',
    name: 'SD-WAN Hybrid',
    description: 'SD-WAN edge connecting to AT&T Core, then Hub reaching AWS and Azure. Unified overlay across MPLS links.',
    nodeCount: 5,
    edgeCount: 4,
    nodes: [
      {
        id: 'sdwan-edge-1',
        type: 'function',
        functionType: 'sdwan',
        x: 60,
        y: 200,
        name: 'SD-WAN Edge',
        icon: 'Layers',
        status: 'active',
        config: {},
      },
      {
        id: 'sdwan-ipe-1',
        type: 'network',
        functionType: 'ipe',
        x: 200,
        y: 200,
        name: 'AT&T Core (IPE)',
        icon: 'Network',
        status: 'active',
        config: {},
      },
      {
        id: 'sdwan-cr-1',
        type: 'function',
        functionType: 'router',
        subType: 'cloud',
        x: 360,
        y: 200,
        name: 'Hub',
        icon: 'hub',
        status: 'active',
        config: {},
      },
      {
        id: 'sdwan-aws-1',
        type: 'destination',
        functionType: 'destination',
        cloudProvider: 'AWS',
        x: 520,
        y: 120,
        name: 'AWS',
        icon: 'Cloud',
        status: 'active',
        config: { provider: 'AWS', region: 'US East' },
      },
      {
        id: 'sdwan-azure-1',
        type: 'destination',
        functionType: 'destination',
        cloudProvider: 'Azure',
        x: 520,
        y: 280,
        name: 'Azure',
        icon: 'Cloud',
        status: 'active',
        config: { provider: 'Azure', region: 'US East' },
      },
    ],
    edges: [
      {
        id: 'sdwan-edge-1-e',
        source: 'sdwan-edge-1',
        target: 'sdwan-ipe-1',
        type: 'MPLS',
        bandwidth: '10 Gbps',
        status: 'active',
      },
      {
        id: 'sdwan-edge-2-e',
        source: 'sdwan-ipe-1',
        target: 'sdwan-cr-1',
        type: 'MPLS',
        bandwidth: '10 Gbps',
        status: 'active',
        config: { resilience: 'redundant' },
      },
      {
        id: 'sdwan-edge-3-e',
        source: 'sdwan-cr-1',
        target: 'sdwan-aws-1',
        type: 'Direct Connect',
        bandwidth: '1 Gbps',
        status: 'active',
      },
      {
        id: 'sdwan-edge-4-e',
        source: 'sdwan-cr-1',
        target: 'sdwan-azure-1',
        type: 'ExpressRoute',
        bandwidth: '1 Gbps',
        status: 'active',
      },
    ],
  },

  // 5. Dual Diverse HA
  {
    id: 'dual-diverse-ha',
    tier: 'geodiversity',
    name: 'Dual Diverse HA',
    description: 'Two IPE nodes and two Hubs in full mesh. Each router connects to both AWS and Azure for maximum resilience.',
    nodeCount: 6,
    edgeCount: 8,
    nodes: [
      {
        id: 'ddha-ipe-1',
        type: 'network',
        functionType: 'ipe',
        x: 120,
        y: 120,
        name: 'AT&T Core A',
        icon: 'Network',
        status: 'active',
        config: {},
      },
      {
        id: 'ddha-ipe-2',
        type: 'network',
        functionType: 'ipe',
        x: 120,
        y: 280,
        name: 'AT&T Core B',
        icon: 'Network',
        status: 'active',
        config: {},
      },
      {
        id: 'ddha-cr-1',
        type: 'function',
        functionType: 'router',
        subType: 'cloud',
        x: 300,
        y: 120,
        name: 'Hub A',
        icon: 'hub',
        status: 'active',
        config: {},
      },
      {
        id: 'ddha-cr-2',
        type: 'function',
        functionType: 'router',
        subType: 'cloud',
        x: 300,
        y: 280,
        name: 'Hub B',
        icon: 'hub',
        status: 'active',
        config: {},
      },
      {
        id: 'ddha-aws-1',
        type: 'destination',
        functionType: 'destination',
        cloudProvider: 'AWS',
        x: 490,
        y: 120,
        name: 'AWS',
        icon: 'Cloud',
        status: 'active',
        config: { provider: 'AWS', region: 'US East' },
      },
      {
        id: 'ddha-azure-1',
        type: 'destination',
        functionType: 'destination',
        cloudProvider: 'Azure',
        x: 490,
        y: 280,
        name: 'Azure',
        icon: 'Cloud',
        status: 'active',
        config: { provider: 'Azure', region: 'US East' },
      },
    ],
    edges: [
      { id: 'ddha-e1', source: 'ddha-ipe-1', target: 'ddha-cr-1', type: 'MPLS', bandwidth: '10 Gbps', status: 'active', config: { resilience: 'dual-diverse' } },
      { id: 'ddha-e2', source: 'ddha-ipe-1', target: 'ddha-cr-2', type: 'MPLS', bandwidth: '10 Gbps', status: 'active', config: { resilience: 'dual-diverse' } },
      { id: 'ddha-e3', source: 'ddha-ipe-2', target: 'ddha-cr-1', type: 'MPLS', bandwidth: '10 Gbps', status: 'active', config: { resilience: 'dual-diverse' } },
      { id: 'ddha-e4', source: 'ddha-ipe-2', target: 'ddha-cr-2', type: 'MPLS', bandwidth: '10 Gbps', status: 'active', config: { resilience: 'dual-diverse' } },
      { id: 'ddha-e5', source: 'ddha-cr-1', target: 'ddha-aws-1', type: 'Direct Connect', bandwidth: '1 Gbps', status: 'active' },
      { id: 'ddha-e6', source: 'ddha-cr-2', target: 'ddha-aws-1', type: 'Direct Connect', bandwidth: '1 Gbps', status: 'active' },
      { id: 'ddha-e7', source: 'ddha-cr-1', target: 'ddha-azure-1', type: 'ExpressRoute', bandwidth: '1 Gbps', status: 'active' },
      { id: 'ddha-e8', source: 'ddha-cr-2', target: 'ddha-azure-1', type: 'ExpressRoute', bandwidth: '1 Gbps', status: 'active' },
    ],
  },

  // 6. Simple VNF Chain
  {
    id: 'simple-vnf-chain',
    tier: 'standard',
    name: 'Simple VNF Chain',
    description: 'AT&T Core (IPE) through a VNF firewall and Hub to AWS. Linear service chain for traffic inspection.',
    nodeCount: 4,
    edgeCount: 3,
    nodes: [
      {
        id: 'vnf-ipe-1',
        type: 'network',
        functionType: 'ipe',
        x: 60,
        y: 200,
        name: 'AT&T Core (IPE)',
        icon: 'Network',
        status: 'active',
        config: {},
      },
      {
        id: 'vnf-fw-1',
        type: 'function',
        functionType: 'firewall',
        x: 220,
        y: 200,
        name: 'VNF Firewall',
        icon: 'Shield',
        status: 'active',
        config: {},
      },
      {
        id: 'vnf-cr-1',
        type: 'function',
        functionType: 'router',
        subType: 'cloud',
        x: 380,
        y: 200,
        name: 'Hub',
        icon: 'hub',
        status: 'active',
        config: {},
      },
      {
        id: 'vnf-aws-1',
        type: 'destination',
        functionType: 'destination',
        cloudProvider: 'AWS',
        x: 540,
        y: 200,
        name: 'AWS',
        icon: 'Cloud',
        status: 'active',
        config: { provider: 'AWS', region: 'US East' },
      },
    ],
    edges: [
      {
        id: 'vnf-edge-1',
        source: 'vnf-ipe-1',
        target: 'vnf-fw-1',
        type: 'MPLS',
        bandwidth: '10 Gbps',
        status: 'active',
        config: { resilience: 'redundant' },
      },
      {
        id: 'vnf-edge-2',
        source: 'vnf-fw-1',
        target: 'vnf-cr-1',
        type: 'Ethernet',
        bandwidth: '1 Gbps',
        status: 'active',
      },
      {
        id: 'vnf-edge-3',
        source: 'vnf-cr-1',
        target: 'vnf-aws-1',
        type: 'Direct Connect',
        bandwidth: '1 Gbps',
        status: 'active',
      },
    ],
  },
  // 7. AWS Max (Auto-Provisioned by AT&T)
  {
    id: 'aws-max-auto',
    name: 'AWS Max (Auto-Provisioned)',
    description: '4 IPEs (Juniper MX-304) across 2 diverse sites in 1 metro. Auto-provisioned by AT&T for Maximum Resiliency.',
    tier: 'maximum',
    providerOnly: 'AWS',
    nodeCount: 7,
    edgeCount: 6,
    nodes: [
      { id: 'awsmax-ipe-1', type: 'network', functionType: 'ipe', x: 80, y: 120, name: 'Path 1', icon: 'Network', status: 'active', config: {}, metro: 'San Jose' },
      { id: 'awsmax-ipe-2', type: 'network', functionType: 'ipe', x: 80, y: 280, name: 'Path 2', icon: 'Network', status: 'active', config: {}, metro: 'San Jose' },
      { id: 'awsmax-ipe-3', type: 'network', functionType: 'ipe', x: 80, y: 440, name: 'Path 3', icon: 'Network', status: 'active', config: {}, metro: 'San Jose' },
      { id: 'awsmax-ipe-4', type: 'network', functionType: 'ipe', x: 80, y: 600, name: 'Path 4', icon: 'Network', status: 'active', config: {}, metro: 'San Jose' },
      { id: 'awsmax-cr-1', type: 'function', functionType: 'router', subType: 'cloud', x: 350, y: 200, name: 'Hub (Site 1)', icon: 'Cloud', status: 'active', config: {} },
      { id: 'awsmax-cr-2', type: 'function', functionType: 'router', subType: 'cloud', x: 350, y: 520, name: 'Hub (Site 2)', icon: 'Cloud', status: 'active', config: {} },
      { id: 'awsmax-aws', type: 'destination', functionType: 'cloud', cloudProvider: 'aws', x: 620, y: 360, name: 'AWS Interconnect – last mile', icon: 'Cloud', status: 'active', config: {} },
    ],
    edges: [
      { id: 'awsmax-e1', source: 'awsmax-ipe-1', target: 'awsmax-cr-1', type: 'Direct Connect', bandwidth: '1 Gbps', status: 'active', config: { resilience: 'ha', bfd: true } },
      { id: 'awsmax-e2', source: 'awsmax-ipe-2', target: 'awsmax-cr-1', type: 'Direct Connect', bandwidth: '1 Gbps', status: 'active', config: { resilience: 'ha', bfd: true } },
      { id: 'awsmax-e3', source: 'awsmax-ipe-3', target: 'awsmax-cr-2', type: 'Direct Connect', bandwidth: '1 Gbps', status: 'active', config: { resilience: 'ha', bfd: true } },
      { id: 'awsmax-e4', source: 'awsmax-ipe-4', target: 'awsmax-cr-2', type: 'Direct Connect', bandwidth: '1 Gbps', status: 'active', config: { resilience: 'ha', bfd: true } },
      { id: 'awsmax-e5', source: 'awsmax-cr-1', target: 'awsmax-aws', type: 'Direct Connect', bandwidth: '1 Gbps', status: 'active' },
      { id: 'awsmax-e6', source: 'awsmax-cr-2', target: 'awsmax-aws', type: 'Direct Connect', bandwidth: '1 Gbps', status: 'active' },
    ],
  },
];
